create table bookmarks(
    id INTEGER primary key generated by default as identity, title text, link text, descript text, rating INTEGER
);

insert into bookmarks(title, link, descript, rating)
values
('Jesse1', 'www.Jesse.com', 'jernf', 3),
('Jesse2', 'www.Jesse.com', 'jernf', 3),
('Jesse3', 'www.Jesse.com', 'jernf', 3),
('Jesse4', 'www.Jesse.com', 'jernf', 3),
('Jesse5', 'www.Jesse.com', 'jernf', 3),
('Jesse6', 'www.Jesse.com', 'jernf', 3),
('Jesse7', 'www.Jesse.com', 'jernf', 3),
('Jesse8', 'www.Jesse.com', 'jernf', 3),
('Jesse9', 'www.Jesse.com', 'jernf', 3),
('Jesse10', 'www.Jesse.com', 'jernf', 3),
('Jesse11', 'www.Jesse.com', 'jernf', 3),
('Jesse12', 'www.Jesse.com', 'jernf', 3),
('Jesse13', 'www.Jesse.com', 'jernf', 3),
('Jesse14', 'www.Jesse.com', 'jernf', 3),
('Jesse15', 'www.Jesse.com', 'jernf', 3),
('Jesse16', 'www.Jesse.com', 'jernf', 3),
('Jesse17', 'www.Jesse.com', 'jernf', 3),
('Jesse18', 'www.Jesse.com', 'jernf', 3);
